import type { Metadata } from "next";
import "./globals.css";
import Providers from "./privider";
import localFont from 'next/font/local';

const myLocalFont = localFont({
  src: '../assets/fonts/yekanBakh/YekanBakhFaNum-VF.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html>
      <body  lang="fa" dir="rtl"
className={myLocalFont.className}
      >

        <Providers>
          {children}
        </Providers>

      </body>
    </html>
  );
}
